BEGIN;

CREATE TABLE IF NOT EXISTS role (
  role_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name varchar(255) NOT NULL UNIQUE,
  role_description varchar(255),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS permission (
  permission_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permission_name varchar(255) NOT NULL UNIQUE,
  permission_description varchar(255),
  is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role_permission_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id integer NOT NULL REFERENCES role(role_id) ON DELETE CASCADE,
  permission_id integer NOT NULL REFERENCES permission(permission_id) ON DELETE CASCADE,
  CONSTRAINT uq_role_permission UNIQUE (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS "user" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) NOT NULL UNIQUE,
  password varchar(255) NOT NULL,
  avatar varchar(2048),
  username varchar(100) NOT NULL UNIQUE,
  full_name varchar(255) NOT NULL,
  is_active boolean NOT NULL DEFAULT false,
  role_id integer REFERENCES role(role_id) ON DELETE SET NULL,
  phone varchar(30),
  refresh_token_hash varchar,
  email_verification_otp_hash varchar,
  email_verification_otp_expires_at timestamp,
  password_reset_otp_hash varchar,
  password_reset_otp_expires_at timestamp,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contract (
  contract_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_number varchar(100) NOT NULL UNIQUE,
  contract_name varchar(255) NOT NULL,
  contract_type varchar(50) NOT NULL,
  contract_owner_type varchar(100) DEFAULT 'TAI_SAN_THI_HANH_AN',
  contract_date date,
  contract_status varchar(50) NOT NULL,
  customer jsonb,
  starting_price numeric(18,2) NOT NULL,
  step_price numeric(18,2) NOT NULL,
  assigned_to integer REFERENCES "user"(id) ON DELETE SET NULL,
  created_by integer REFERENCES "user"(id) ON DELETE SET NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_contract_status ON contract(contract_status);

CREATE TABLE IF NOT EXISTS property (
  property_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_name varchar(255) NOT NULL,
  property_type varchar(100) NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contract_property (
  contract_property_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_id integer NOT NULL REFERENCES contract(contract_id) ON DELETE CASCADE,
  property_id integer NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_contract_property UNIQUE (contract_id, property_id)
);

CREATE TABLE IF NOT EXISTS regulation (
  regulation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  regulation_number varchar(100) NOT NULL UNIQUE,
  starting_price numeric(18,2) NOT NULL,
  deposit_amount numeric(18,2) NOT NULL,
  step_price numeric(18,2) NOT NULL,
  registration_fee numeric(18,2) NOT NULL,
  start_register_date timestamptz NOT NULL,
  end_register_date timestamptz NOT NULL,
  auction_date timestamptz NOT NULL,
  auction_time time NOT NULL,
  auction_format varchar(100) NOT NULL,
  auction_method varchar(100) NOT NULL,
  contract_id integer NOT NULL REFERENCES contract(contract_id) ON DELETE CASCADE,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auction_result (
  auction_result_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auction_result_number varchar(100) NOT NULL UNIQUE,
  winner jsonb NOT NULL,
  winning_price numeric(18,2) NOT NULL,
  completed_at timestamptz NOT NULL,
  auction_status varchar(50) NOT NULL,
  contract_id integer NOT NULL REFERENCES contract(contract_id) ON DELETE CASCADE,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS announcement (
  announcement_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  announcement_number varchar(100) NOT NULL UNIQUE,
  starting_price numeric(18,2) NOT NULL,
  deposit_amount numeric(18,2) NOT NULL,
  step_price numeric(18,2) NOT NULL,
  registration_fee numeric(18,2) NOT NULL,
  start_register_date timestamptz NOT NULL,
  end_register_date timestamptz NOT NULL,
  auction_date timestamptz NOT NULL,
  auction_time time NOT NULL,
  auction_format varchar(100) NOT NULL,
  auction_method varchar(100) NOT NULL,
  contract_id integer NOT NULL REFERENCES contract(contract_id) ON DELETE CASCADE,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_announcement_dates CHECK (
    start_register_date <= end_register_date
    AND end_register_date <= auction_date
  )
);

CREATE TABLE IF NOT EXISTS configuration (
  config_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key varchar(100) NOT NULL UNIQUE,
  name varchar(255) NOT NULL,
  description text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS file (
  file_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bucket varchar(255) NOT NULL,
  object_key varchar(1024) NOT NULL,
  original_name varchar(255) NOT NULL,
  content_type varchar(255) NOT NULL,
  size bigint NOT NULL CHECK (size >= 0),
  etag varchar(255),
  entity_type varchar(50) NOT NULL,
  entity_id integer NOT NULL,
  uploaded_by integer REFERENCES "user"(id) ON DELETE SET NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_file_s3_object UNIQUE (bucket, object_key)
);
CREATE INDEX IF NOT EXISTS idx_file_entity ON file(entity_type, entity_id);

-- Baseline data. All inserts are repeatable and safe to run more than once.
INSERT INTO role (role_name, role_description, is_active)
VALUES
  ('admin', 'Full system administrator', true),
  ('staff', 'Auction management staff', true)
ON CONFLICT (role_name) DO NOTHING;

INSERT INTO permission (permission_name, permission_description, is_active)
VALUES
  ('contracts.create', 'Create contracts', true),
  ('contracts.read', 'View contracts', true),
  ('contracts.update', 'Update contracts', true),
  ('contracts.delete', 'Delete contracts', true),
  ('users.create', 'Create users', true),
  ('users.read', 'View users', true),
  ('users.update', 'Update users', true),
  ('users.delete', 'Delete users', true)
ON CONFLICT (permission_name) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r
CROSS JOIN permission p
WHERE r.role_name = 'admin'
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r
JOIN permission p ON p.permission_name IN ('contracts.create', 'contracts.read', 'contracts.update')
WHERE r.role_name = 'staff'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- The password is the scrypt hash for the local development password
-- "Password123!". Change it before using this seed in a real environment.
INSERT INTO "user" (email, password, username, full_name, is_active, role_id, phone)
SELECT 'admin@example.com',
       'scrypt$bG9jYWwtZGV2ZWxvcG1lbnQtc2FsdA==$8iD8lScgb+C67fMXuyFvNtTdJrP4K1GisuQS0ElYpJLj34sGhsyzrIh1JAA4wN0fUkicFPGOWoCZE01GyMIesQ==',
       'admin', 'System Administrator', true, role_id, '+84000000000'
FROM role
WHERE role_name = 'admin'
ON CONFLICT (email) DO NOTHING;

INSERT INTO property (property_name, property_type)
SELECT v.property_name, v.property_type
FROM (VALUES
  ('Downtown commercial land lot', 'Land'),
  ('Warehouse building', 'Building')
) AS v(property_name, property_type)
WHERE NOT EXISTS (
  SELECT 1 FROM property p WHERE p.property_name = v.property_name
);

INSERT INTO contract (
  contract_number, contract_name, contract_type, contract_owner_type, contract_date,
  contract_status, customer, starting_price, step_price, assigned_to, created_by
)
SELECT 'CT-2026-0001', 'Downtown commercial land auction', 'HOP_DONG_MOI',
       'TAI_SAN_THI_HANH_AN', DATE '2026-01-01',
       'MOI', '{"name":"Example Customer","taxCode":"0000000000"}'::jsonb,
       1000000000.00, 10000000.00, u.i, u.i
FROM "user" u
WHERE u.email = 'admin@example.com'
ON CONFLICT (contract_number) DO NOTHING;

INSERT INTO contract_property (contract_id, property_id)
SELECT c.contract_id, p.property_id
FROM contract c
JOIN property p ON p.property_name IN ('Downtown commercial land lot', 'Warehouse building')
WHERE c.contract_number = 'CT-2026-0001'
ON CONFLICT (contract_id, property_id) DO NOTHING;

INSERT INTO regulation (
  regulation_number, starting_price, deposit_amount, step_price, registration_fee,
  start_register_date, end_register_date, auction_date, auction_time,
  auction_format, auction_method, contract_id
)
SELECT 'REG-2026-0001', 1000000000.00, 100000000.00, 10000000.00, 1000000.00,
       '2026-08-01 00:00:00+07', '2026-08-14 23:59:59+07',
       '2026-08-20 00:00:00+07', '09:30', 'Online', 'Ascending bid', c.contract_id
FROM contract c
WHERE c.contract_number = 'CT-2026-0001'
ON CONFLICT (regulation_number) DO NOTHING;

INSERT INTO announcement (
  announcement_number, starting_price, deposit_amount, step_price, registration_fee,
  start_register_date, end_register_date, auction_date, auction_time,
  auction_format, auction_method, contract_id
)
SELECT 'ANN-2026-0001', 1000000000.00, 100000000.00, 10000000.00, 1000000.00,
       '2026-08-01 00:00:00+07', '2026-08-14 23:59:59+07',
       '2026-08-20 00:00:00+07', '09:30', 'Online', 'Ascending bid', c.contract_id
FROM contract c
WHERE c.contract_number = 'CT-2026-0001'
ON CONFLICT (announcement_number) DO NOTHING;

INSERT INTO configuration (key, name, description)
VALUES
  ('auction.default_currency', 'Default currency', 'Currency used for auction monetary values'),
  ('auction.registration_enabled', 'Registration enabled', 'Controls whether auction registration is enabled')
ON CONFLICT (key) DO NOTHING;

COMMIT;
